spring.jpa.open-in-view=false

server.port=${SERVER_PORT:9000}
server.servlet.session.cookie.name=AS_DSBOOKS_SESSION

app.security.issuer=${APP_ISSUER_URL:http://localhost:9000}

#logging.level.org.springframework.web.servlet.view=DEBUG
#logging.level.org.thymeleaf=DEBUG