# H2 in-memory database connection
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Log SQL statements to the console
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Allow import.sql to use multi-line statements (delimited by ; instead 0f newline)
spring.jpa.properties.hibernate.hbm2ddl.import_files_sql_extractor=org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor

spring.jpa.open-in-view=false

server.port=${SERVER_PORT:9000}

server.servlet.session.cookie.name=AS_DSBOOKS_SESSION

app.security.issuer=${APP_ISSUER_URL:http://localhost:9000}

#logging.level.org.springframework.web.servlet.view=DEBUG
#logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.security=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always